name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

env:
  NEXT_PUBLIC_API_BASE_URL: "https://dev-uks-webapp-authcontract-backend-dhezfde0azfzhbhg.uksouth-01.azurewebsites.net"
  NEXT_PUBLIC_AZURE_CLIENT_ID: "94a05d5a-51ac-4bc2-884f-5ef3211752b1"
  NEXT_PUBLIC_AZURE_REDIRECT_URI: "https://black-ground-0c4528a03.4.azurestaticapps.net/auth/callback"
  NEXT_PUBLIC_AZURE_TENANT_ID: "cb8d0f5e-295e-44f1-8cab-184ae827c864"
  NEXT_PUBLIC_AZURE_AUTHORIZE_URL: "https://login.microsoftonline.com/cb8d0f5e-295e-44f1-8cab-184ae827c864/oauth2/v2.0/authorize"
  NEXT_PUBLIC_AZURE_SCOPE: "email openid profile offline_access https://graph.microsoft.com/.default"

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_CLIFF_09CED060F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_CLIFF_09CED060F }}
          action: "close"
